<?php

// Exit if accessed directly.
defined( 'ABSPATH' ) || exit;

$copyright = sprintf( 'Copyright © %s - %s', gmdate( 'Y' ), get_bloginfo( 'name' ) );

CSF::createSection(
	$prefix,
	array(
		'parent' => 'general',
		'title'  => __( 'Main', 'wds-notrans' ),
		'fields' => array(
			array(
				'type'  => 'heading',
				'title' => __( 'Branding', 'wds-notrans' ),
			),
			array(
				'id'      => 'favicon',
				'type'    => 'upload',
				'library' => 'image',
				'preview' => true,
				'title'   => __( 'Icon', 'weddingsaas' ),
				'desc'    => __( 'Ukuran yang disarankan adalah 256 X 256 piksel.', 'weddingsaas' ),
				'default' => wds_v1_option( 'icon_branding' ),
			),
			array(
				'id'      => 'logo_light',
				'type'    => 'upload',
				'library' => 'image',
				'preview' => true,
				'title'   => __( 'Logo untuk Mode Terang', 'weddingsaas' ),
				'desc'    => __( 'Ukuran yang disarankan adalah 365 X 70 piksel.', 'weddingsaas' ),
				'default' => wds_v1_option( 'logo_branding' ),
			),
			array(
				'id'      => 'logo_dark',
				'type'    => 'upload',
				'library' => 'image',
				'preview' => true,
				'title'   => __( 'Logo untuk Mode Gelap', 'weddingsaas' ),
				'desc'    => __( 'Ukuran yang disarankan adalah 365 X 70 piksel.', 'weddingsaas' ),
				'default' => wds_v1_option( 'logo_branding_dark' ),
			),
			array(
				'id'      => 'bg_light',
				'type'    => 'upload',
				'library' => 'image',
				'preview' => true,
				'title'   => __( 'Background untuk Mode Terang', 'weddingsaas' ),
				'desc'    => __( 'Ukuran yang disarankan adalah 1920 X 1080 piksel.', 'weddingsaas' ),
				'default' => wds_v1_option( 'bg_light' ),
			),
			array(
				'id'      => 'bg_dark',
				'type'    => 'upload',
				'library' => 'image',
				'preview' => true,
				'title'   => __( 'Background untuk Mode Gelap', 'weddingsaas' ),
				'desc'    => __( 'Ukuran yang disarankan adalah 1920 X 1080 piksel.', 'weddingsaas' ),
				'default' => wds_v1_option( 'bg_dark' ),
			),
			array(
				'id'      => 'placeholder',
				'type'    => 'upload',
				'library' => 'image',
				'preview' => true,
				'title'   => __( 'Thumbnail Placeholder', 'wds-notrans' ),
				'desc'    => __( 'Ukuran yang disarankan adalah 256 X 256 piksel.', 'weddingsaas' ),
				'default' => wds_v1_option( 'thumbnail_placeholder' ),
			),
			array(
				'id'      => 'category_icon',
				'type'    => 'upload',
				'library' => 'image',
				'preview' => true,
				'title'   => __( 'Icon Semua Kategori', 'weddingsaas' ),
				'desc'    => __( 'Ukuran yang disarankan adalah 64 X 64 piksel.', 'weddingsaas' ),
				'default' => wds_v1_option( 'category_icon_all' ),
			),
			array(
				'id'          => 'tagline',
				'type'        => 'text',
				'title'       => __( 'Tagline', 'wds-notrans' ),
				'placeholder' => 'All in one Wedding Service Management',
				'default'     => wds_v1_option( 'tagline', 'All in one Wedding Service Management' ),
			),
			array(
				'id'          => 'copyright',
				'type'        => 'text',
				'title'       => __( 'Copyright', 'wds-notrans' ),
				'placeholder' => $copyright,
				'default'     => wds_v1_option( 'copyright', $copyright ),
			),

			array(
				'type'  => 'heading',
				'title' => __( 'Custome Color', 'wds-notrans' ),
			),
			array(
				'id'      => 'default_mode',
				'type'    => 'select',
				'title'   => __( 'Default Mode', 'wds-notrans' ),
				'options' => array(
					'light' => __( 'Light Mode', 'wds-notrans' ),
					'dark'  => __( 'Dark Mode', 'wds-notrans' ),
				),
				'default' => wds_v1_option( 'default_mode', 'light' ),
			),
			array(
				'id'      => 'custome_color',
				'type'    => 'switcher',
				'title'   => __( 'Enable Custome Color', 'wds-notrans' ),
				'default' => true,
			),
			array(
				'id'         => 'default_color',
				'type'       => 'color_group',
				'title'      => __( 'Default Color', 'wds-notrans' ),
				'options'    => array(
					'primary' => __( 'Primary', 'wds-notrans' ),
					'success' => __( 'Success', 'wds-notrans' ),
					'info'    => __( 'Info', 'wds-notrans' ),
					'warning' => __( 'Warning', 'wds-notrans' ),
					'danger'  => __( 'Danger', 'wds-notrans' ),
				),
				'default'    => array(
					'primary' => wds_v1_option( 'primary_color', '#009EF7' ),
					'success' => wds_v1_option( 'success_color', '#50cd89' ),
					'info'    => wds_v1_option( 'info_color', '#7239ea' ),
					'warning' => wds_v1_option( 'warning_color', '#ffc700' ),
					'danger'  => wds_v1_option( 'danger_color', '#f1416c' ),
				),
				'dependency' => array( 'custome_color', '==', 'true' ),
			),
			array(
				'id'         => 'default_active_color',
				'type'       => 'color_group',
				'title'      => __( 'Default Active Color', 'wds-notrans' ),
				'options'    => array(
					'primary' => __( 'Primary', 'wds-notrans' ),
					'success' => __( 'Success', 'wds-notrans' ),
					'info'    => __( 'Info', 'wds-notrans' ),
					'warning' => __( 'Warning', 'wds-notrans' ),
					'danger'  => __( 'Danger', 'wds-notrans' ),
				),
				'default'    => array(
					'primary' => wds_v1_option( 'primary_hover_color', '#0095e8' ),
					'success' => wds_v1_option( 'success_hover_color', '#47be7d' ),
					'info'    => wds_v1_option( 'info_hover_color', '#5014d0' ),
					'warning' => wds_v1_option( 'warning_hover_color', '#f1bc00' ),
					'danger'  => wds_v1_option( 'danger_hover_color', '#d9214e' ),
				),
				'dependency' => array( 'custome_color', '==', 'true' ),
			),
			array(
				'id'         => 'topbar_color',
				'type'       => 'color',
				'title'      => __( 'Topbar Color', 'wds-notrans' ),
				'default'    => wds_v1_option( 'topbar_color', '#1e1e2d' ),
				'dependency' => array( 'custome_color', '==', 'true' ),
			),
			array(
				'id'         => 'menu_color',
				'type'       => 'color',
				'title'      => __( 'Menu Color', 'wds-notrans' ),
				'default'    => '#FFFFFF',
				'dependency' => array( 'custome_color', '==', 'true' ),
			),

			array(
				'type'  => 'heading',
				'title' => __( 'Custom Icon', 'wds-notrans' ),
			),
			array(
				'id'      => 'icon_1',
				'type'    => 'upload',
				'library' => 'image',
				'preview' => true,
				'title'   => __( 'Status Akun', 'weddingsaas' ),
				'desc'    => __( 'Ukuran yang disarankan adalah 64 X 64 piksel.', 'weddingsaas' ),
				'default' => wds_v1_option( 'icon_overview_1' ),
			),
			array(
				'id'      => 'icon_2',
				'type'    => 'upload',
				'library' => 'image',
				'preview' => true,
				'title'   => __( 'Membership', 'weddingsaas' ),
				'desc'    => __( 'Ukuran yang disarankan adalah 64 X 64 piksel.', 'weddingsaas' ),
				'default' => wds_v1_option( 'icon_overview_2' ),
			),
			array(
				'id'      => 'icon_3',
				'type'    => 'upload',
				'library' => 'image',
				'preview' => true,
				'title'   => __( 'Masa Aktif', 'weddingsaas' ),
				'desc'    => __( 'Ukuran yang disarankan adalah 64 X 64 piksel.', 'weddingsaas' ),
				'default' => wds_v1_option( 'icon_overview_3' ),
			),
			array(
				'id'      => 'icon_4',
				'type'    => 'upload',
				'library' => 'image',
				'preview' => true,
				'title'   => __( 'Total Ucapan', 'weddingsaas' ),
				'desc'    => __( 'Ukuran yang disarankan adalah 64 X 64 piksel.', 'weddingsaas' ),
				'default' => wds_v1_option( 'icon_overview_4' ),
			),
			array(
				'id'      => 'icon_5',
				'type'    => 'upload',
				'library' => 'image',
				'preview' => true,
				'title'   => __( 'Total Undangan', 'weddingsaas' ),
				'desc'    => __( 'Ukuran yang disarankan adalah 64 X 64 piksel.', 'weddingsaas' ),
				'default' => wds_v1_option( 'icon_overview_5' ),
			),
			array(
				'id'      => 'icon_6',
				'type'    => 'upload',
				'library' => 'image',
				'preview' => true,
				'title'   => __( 'Kuota Undangan', 'weddingsaas' ),
				'desc'    => __( 'Ukuran yang disarankan adalah 64 X 64 piksel.', 'weddingsaas' ),
				'default' => wds_v1_option( 'icon_overview_6' ),
			),
			array(
				'id'      => 'icon_7',
				'type'    => 'upload',
				'library' => 'image',
				'preview' => true,
				'title'   => __( 'Total Client', 'weddingsaas' ),
				'desc'    => __( 'Ukuran yang disarankan adalah 64 X 64 piksel.', 'weddingsaas' ),
				'default' => wds_v1_option( 'icon_overview_7' ),
			),
			array(
				'id'      => 'icon_8',
				'type'    => 'upload',
				'library' => 'image',
				'preview' => true,
				'title'   => __( 'Kuota Client', 'weddingsaas' ),
				'desc'    => __( 'Ukuran yang disarankan adalah 64 X 64 piksel.', 'weddingsaas' ),
				'default' => wds_v1_option( 'icon_overview_8' ),
			),
			array(
				'id'      => 'icon_9',
				'type'    => 'upload',
				'library' => 'image',
				'preview' => true,
				'title'   => __( 'Total Pendapatan', 'weddingsaas' ),
				'desc'    => __( 'Ukuran yang disarankan adalah 64 X 64 piksel.', 'weddingsaas' ),
				'default' => wds_v1_option( 'icon_overview_9' ),
			),

			array(
				'type'  => 'heading',
				'title' => __( 'Custome Scripts', 'wds-notrans' ),
			),
			array(
				'id'       => 'header_scripts',
				'type'     => 'code_editor',
				'title'    => __( 'Header Scripts', 'wds-notrans' ),
				'sanitize' => false,
				'settings' => array(
					'theme' => 'ambiance',
					'mode'  => 'htmlmixed',
				),
				'default'  => wds_v1_option( 'header_scripts' ),
			),
			array(
				'id'       => 'footer_scripts',
				'type'     => 'code_editor',
				'title'    => __( 'Footer Scripts', 'wds-notrans' ),
				'sanitize' => false,
				'settings' => array(
					'theme' => 'ambiance',
					'mode'  => 'htmlmixed',
				),
				'default'  => wds_v1_option( 'footer_scripts' ),
			),
		),
	)
);
